name: Deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    name: build and deploy
    runs-on: ubuntu-latest
    permissions:
      # only required for workflows in private repositories
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 17.8
          cache: 'npm'
      - run: npm ci
        
      - name: build
        run: npm run build

      - name: Deploy to AWS
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_EC2_RSA_KEY }}
          REMOTE_HOST: ${{ secrets.AWS_HOST }}
          REMOTE_USER: ${{ secrets.AWS_USERNAME }}
          SOURCE: "dist/"
          TARGET: ~/my-project
