name: Release
on:
  push:
    tags:
      - "v*.*.*"
        
jobs:
  zip-file:
    name: Zip and remove unnecessary the files
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: little-core-labs/get-git-tag@v3.0.1
        id: tagName
      - uses: actions/checkout@v3
      - run: ./.github/scripts/release/cprelease.sh
      - run: ./.github/scripts/release/comment.sh
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r my-project-${{ steps.tagName.outputs.tag }}.zip release

      - uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          files: my-project-${{ steps.tagName.outputs.tag }}.zip
