name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Do testing
    runs-on: ubuntu-latest
    permissions:
      # only required for workflows in private repositories
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      
      - name: Setup Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 17.8
          cache: 'npm'
      - run: npm ci

      - name: make environment
        run: echo WEATHERKEY=${{ secrets.WEATHERKEY }} >> server/.env

      - name: Run tests
        run: npm run test
